"""work pls

Revision ID: 5675ef43e4db
Revises: d33e92dcc78f
Create Date: 2023-05-28 02:29:17.784542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5675ef43e4db'
down_revision = 'd33e92dcc78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
